stages:
  - build-svelte
  - build-dotnet
  - build-docker

variables:
  IMAGE_TAG: v0.0.2
  IMAGE_NAME: saverwalter

build-svelte:
  stage: build-svelte
  image: node:18-alpine3.17
  script:
    - cd Deeplex.Saverwalter.WebAPI/svelte
    - yarn install
    - yarn build
  artifacts:
    paths:
      - /builds/klawr/saverwalter/Deeplex.Saverwalter.WebAPI/wwwroot

build-dotnet:
  stage: build-dotnet
  image: mcr.microsoft.com/devcontainers/dotnet:0-6.0
  script:
    - cd Deeplex.Saverwalter.WebAPI
    - dotnet restore
    - dotnet publish -c release
  artifacts:
    paths:
      - /builds/klawr/saverwalter/Deeplex.Saverwalter.WebAPI/bin

build-docker:
  stage: build-docker
  image: docker:23.0
  script:
    - cd Deeplex.Saverwalter.WebAPI
    - if docker image inspect "${IMAGE_NAME}:${IMAGE_TAG}" >/dev/null 2>&1; then
    - echo "Image ${IMAGE_NAME}:${IMAGE_TAG} already exists. Skipping build."
    - else
    - echo "Image ${IMAGE_NAME}:${IMAGE_TAG} does not exist. Building..."
    - docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" .
    - fi
