stages:
  - build
  - notify

include:
  project: deeplex/templates
  file: Notify.gitlab-ci.yml

variables:
  IMAGE_NAME: saverwalter

build-svelte:
  stage: build
  image: node:18-alpine3.17
  script:
    - cd Deeplex.Saverwalter.WebAPI/svelte
    - yarn install
    - yarn build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Deeplex.Saverwalter.WebAPI/wwwroot

build-dotnet:
  stage: build
  image: mcr.microsoft.com/devcontainers/dotnet:0-6.0
  script:
    - cd Deeplex.Saverwalter.WebAPI
    - dotnet restore
    - dotnet publish -c release
  artifacts:
    paths:
      - $CI_PROJECT_DIR/Deeplex.Saverwalter.WebAPI/bin

build-docker:
  stage: build
  image: docker:23.0
  needs:
    - build-svelte
    - build-dotnet
  dependencies:
    - build-svelte
    - build-dotnet
  script:
    - cd Deeplex.Saverwalter.WebAPI
    - if [[ ! "$CI_COMMIT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    - echo "CI_COMMIT_TAG ($CI_COMMIT_TAG) does not match pattern v0.0.0. Skipping build.";
    - exit 1
    - elif docker image inspect "${IMAGE_NAME}:${CI_COMMIT_TAG}" >/dev/null 2>&1; then
    - echo "Image $IMAGE_NAME:$CI_COMMIT_TAG already exists. Skipping build.";
    - else
    - echo "Image $IMAGE_NAME:$CI_COMMIT_TAG does not exist. Building...";
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_TAG" .
    - fi
  only:
    - tags