version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    image: postgres:14-alpine3.16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTRES_DB=walter_dev_full_generic_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data

  s3:
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    restart: unless-stopped
    volumes:
      - s3-data:/data
    command: server --console-address ":9001" /data

volumes:
  postgres-data:
  s3-data:
