// <auto-generated />
using System;
using Deeplex.Saverwalter.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deeplex.Saverwalter.Model.Migrations.Npgsql
{
    [DbContext(typeof(SaverwalterContext))]
    [Migration("20250808201634_AbrechnungsresultatNotiz")]
    partial class AbrechnungsresultatNotiz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Abrechnungsresultat", b =>
                {
                    b.Property<Guid>("AbrechnungsresultatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("abrechnungsresultat_id");

                    b.Property<bool>("Abgesendet")
                        .HasColumnType("boolean")
                        .HasColumnName("abgesendet");

                    b.Property<bool>("IstBeglichen")
                        .HasColumnType("boolean")
                        .HasColumnName("ist_beglichen");

                    b.Property<int>("Jahr")
                        .HasColumnType("integer")
                        .HasColumnName("jahr");

                    b.Property<double>("Kaltmiete")
                        .HasColumnType("double precision")
                        .HasColumnName("kaltmiete");

                    b.Property<double>("Minderung")
                        .HasColumnType("double precision")
                        .HasColumnName("minderung");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<double>("Rechnungsbetrag")
                        .HasColumnType("double precision")
                        .HasColumnName("rechnungsbetrag");

                    b.Property<int>("VertragId")
                        .HasColumnType("integer")
                        .HasColumnName("vertrag_id");

                    b.Property<double>("Vorauszahlung")
                        .HasColumnType("double precision")
                        .HasColumnName("vorauszahlung");

                    b.HasKey("AbrechnungsresultatId")
                        .HasName("pk_abrechnungsresultate");

                    b.HasIndex("VertragId")
                        .HasDatabaseName("ix_abrechnungsresultate_vertrag_id");

                    b.ToTable("abrechnungsresultate", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adresse_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdresseId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Hausnummer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hausnummer");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<string>("Postleitzahl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postleitzahl");

                    b.Property<string>("Stadt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stadt");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("strasse");

                    b.HasKey("AdresseId")
                        .HasName("pk_adressen");

                    b.ToTable("adressen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Auth.Pbkdf2PasswordCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Iterations")
                        .HasColumnType("integer")
                        .HasColumnName("iterations");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_pbkdf2password_credentials");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_pbkdf2password_credentials_user_id");

                    b.ToTable("pbkdf2password_credentials", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Auth.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int?>("KontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("kontakt_id");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("KontaktId")
                        .HasDatabaseName("ix_user_accounts_kontakt_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_username");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Auth.UserResetCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Token")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_reset_credentials");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_user_reset_credentials_token");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_reset_credentials_user_id");

                    b.ToTable("user_reset_credentials", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Betriebskostenrechnung", b =>
                {
                    b.Property<int>("BetriebskostenrechnungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("betriebskostenrechnung_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BetriebskostenrechnungId"));

                    b.Property<double>("Betrag")
                        .HasColumnType("double precision")
                        .HasColumnName("betrag");

                    b.Property<int>("BetreffendesJahr")
                        .HasColumnType("integer")
                        .HasColumnName("betreffendes_jahr");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("UmlageId")
                        .HasColumnType("integer")
                        .HasColumnName("umlage_id");

                    b.HasKey("BetriebskostenrechnungId")
                        .HasName("pk_betriebskostenrechnungen");

                    b.HasIndex("UmlageId")
                        .HasDatabaseName("ix_betriebskostenrechnungen_umlage_id");

                    b.ToTable("betriebskostenrechnungen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Erhaltungsaufwendung", b =>
                {
                    b.Property<int>("ErhaltungsaufwendungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("erhaltungsaufwendung_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ErhaltungsaufwendungId"));

                    b.Property<int>("AusstellerKontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("aussteller_kontakt_id");

                    b.Property<double>("Betrag")
                        .HasColumnType("double precision")
                        .HasColumnName("betrag");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bezeichnung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("WohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnung_id");

                    b.HasKey("ErhaltungsaufwendungId")
                        .HasName("pk_erhaltungsaufwendungen");

                    b.HasIndex("AusstellerKontaktId")
                        .HasDatabaseName("ix_erhaltungsaufwendungen_aussteller_kontakt_id");

                    b.HasIndex("WohnungId")
                        .HasDatabaseName("ix_erhaltungsaufwendungen_wohnung_id");

                    b.ToTable("erhaltungsaufwendungen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Garage", b =>
                {
                    b.Property<int>("GarageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("garage_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GarageId"));

                    b.Property<int?>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("adresse_id");

                    b.Property<int>("BesitzerKontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("besitzer_kontakt_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Kennung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kennung");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.HasKey("GarageId")
                        .HasName("pk_garagen");

                    b.HasIndex("AdresseId")
                        .HasDatabaseName("ix_garagen_adresse_id");

                    b.HasIndex("BesitzerKontaktId")
                        .HasDatabaseName("ix_garagen_besitzer_kontakt_id");

                    b.ToTable("garagen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.HKVO", b =>
                {
                    b.Property<int>("HKVOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hkvo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HKVOId"));

                    b.Property<int>("BetriebsstromUmlageId")
                        .HasColumnType("integer")
                        .HasColumnName("betriebsstrom_umlage_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("HKVO_P7")
                        .HasColumnType("double precision")
                        .HasColumnName("hkvo_p7");

                    b.Property<double>("HKVO_P8")
                        .HasColumnType("double precision")
                        .HasColumnName("hkvo_p8");

                    b.Property<int>("HKVO_P9")
                        .HasColumnType("integer")
                        .HasColumnName("hkvo_p9");

                    b.Property<int>("HeizkostenId")
                        .HasColumnType("integer")
                        .HasColumnName("heizkosten_id");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<double>("Strompauschale")
                        .HasColumnType("double precision")
                        .HasColumnName("strompauschale");

                    b.HasKey("HKVOId")
                        .HasName("pk_hkvo");

                    b.HasIndex("BetriebsstromUmlageId")
                        .HasDatabaseName("ix_hkvo_betriebsstrom_umlage_id");

                    b.HasIndex("HeizkostenId")
                        .IsUnique()
                        .HasDatabaseName("ix_hkvo_heizkosten_id");

                    b.ToTable("hkvo", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Kontakt", b =>
                {
                    b.Property<int>("KontaktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("kontakt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KontaktId"));

                    b.Property<int?>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("adresse_id");

                    b.Property<int>("Anrede")
                        .HasColumnType("integer")
                        .HasColumnName("anrede");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasColumnType("text")
                        .HasColumnName("fax");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Mobil")
                        .HasColumnType("text")
                        .HasColumnName("mobil");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("Rechtsform")
                        .HasColumnType("integer")
                        .HasColumnName("rechtsform");

                    b.Property<string>("Telefon")
                        .HasColumnType("text")
                        .HasColumnName("telefon");

                    b.Property<string>("Vorname")
                        .HasColumnType("text")
                        .HasColumnName("vorname");

                    b.HasKey("KontaktId")
                        .HasName("pk_kontakte");

                    b.HasIndex("AdresseId")
                        .HasDatabaseName("ix_kontakte_adresse_id");

                    b.ToTable("kontakte", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Konto", b =>
                {
                    b.Property<int>("KontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("konto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KontoId"));

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank");

                    b.Property<int>("BesitzerKontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("besitzer_kontakt_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.HasKey("KontoId")
                        .HasName("pk_kontos");

                    b.HasIndex("BesitzerKontaktId")
                        .HasDatabaseName("ix_kontos_besitzer_kontakt_id");

                    b.ToTable("kontos", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Miete", b =>
                {
                    b.Property<int>("MieteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("miete_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MieteId"));

                    b.Property<double>("Betrag")
                        .HasColumnType("double precision")
                        .HasColumnName("betrag");

                    b.Property<DateOnly>("BetreffenderMonat")
                        .HasColumnType("date")
                        .HasColumnName("betreffender_monat");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("VertragId")
                        .HasColumnType("integer")
                        .HasColumnName("vertrag_id");

                    b.Property<DateOnly>("Zahlungsdatum")
                        .HasColumnType("date")
                        .HasColumnName("zahlungsdatum");

                    b.HasKey("MieteId")
                        .HasName("pk_mieten");

                    b.HasIndex("VertragId")
                        .HasDatabaseName("ix_mieten_vertrag_id");

                    b.ToTable("mieten", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Mietminderung", b =>
                {
                    b.Property<int>("MietminderungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mietminderung_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MietminderungId"));

                    b.Property<DateOnly>("Beginn")
                        .HasColumnType("date")
                        .HasColumnName("beginn");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("Ende")
                        .HasColumnType("date")
                        .HasColumnName("ende");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("Minderung")
                        .HasColumnType("double precision")
                        .HasColumnName("minderung");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("VertragId")
                        .HasColumnType("integer")
                        .HasColumnName("vertrag_id");

                    b.HasKey("MietminderungId")
                        .HasName("pk_mietminderungen");

                    b.HasIndex("VertragId")
                        .HasDatabaseName("ix_mietminderungen_vertrag_id");

                    b.ToTable("mietminderungen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Umlage", b =>
                {
                    b.Property<int>("UmlageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("umlage_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UmlageId"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text")
                        .HasColumnName("beschreibung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("Schluessel")
                        .HasColumnType("integer")
                        .HasColumnName("schluessel");

                    b.Property<int>("TypUmlagetypId")
                        .HasColumnType("integer")
                        .HasColumnName("typ_umlagetyp_id");

                    b.HasKey("UmlageId")
                        .HasName("pk_umlagen");

                    b.HasIndex("TypUmlagetypId")
                        .HasDatabaseName("ix_umlagen_typ_umlagetyp_id");

                    b.ToTable("umlagen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Umlagetyp", b =>
                {
                    b.Property<int>("UmlagetypId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("umlagetyp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UmlagetypId"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bezeichnung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.HasKey("UmlagetypId")
                        .HasName("pk_umlagetypen");

                    b.ToTable("umlagetypen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Vertrag", b =>
                {
                    b.Property<int>("VertragId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vertrag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VertragId"));

                    b.Property<int?>("AnsprechpartnerKontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("ansprechpartner_kontakt_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("Ende")
                        .HasColumnType("date")
                        .HasColumnName("ende");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("WohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnung_id");

                    b.HasKey("VertragId")
                        .HasName("pk_vertraege");

                    b.HasIndex("AnsprechpartnerKontaktId")
                        .HasDatabaseName("ix_vertraege_ansprechpartner_kontakt_id");

                    b.HasIndex("WohnungId")
                        .HasDatabaseName("ix_vertraege_wohnung_id");

                    b.ToTable("vertraege", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.VertragVersion", b =>
                {
                    b.Property<int>("VertragVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vertrag_version_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VertragVersionId"));

                    b.Property<DateOnly>("Beginn")
                        .HasColumnType("date")
                        .HasColumnName("beginn");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Grundmiete")
                        .HasColumnType("double precision")
                        .HasColumnName("grundmiete");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("Personenzahl")
                        .HasColumnType("integer")
                        .HasColumnName("personenzahl");

                    b.Property<int>("VertragId")
                        .HasColumnType("integer")
                        .HasColumnName("vertrag_id");

                    b.HasKey("VertragVersionId")
                        .HasName("pk_vertrag_versionen");

                    b.HasIndex("VertragId")
                        .HasDatabaseName("ix_vertrag_versionen_vertrag_id");

                    b.ToTable("vertrag_versionen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.VertragsBetriebskostenrechnung", b =>
                {
                    b.Property<int>("VertragsBetriebskostenrechnungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vertrags_betriebskostenrechnung_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VertragsBetriebskostenrechnungId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("RechnungBetriebskostenrechnungId")
                        .HasColumnType("integer")
                        .HasColumnName("rechnung_betriebskostenrechnung_id");

                    b.Property<int>("VertragId")
                        .HasColumnType("integer")
                        .HasColumnName("vertrag_id");

                    b.HasKey("VertragsBetriebskostenrechnungId")
                        .HasName("pk_vertrags_betriebskostenrechnung");

                    b.HasIndex("RechnungBetriebskostenrechnungId")
                        .HasDatabaseName("ix_vertrags_betriebskostenrechnung_rechnung_betriebskostenrech");

                    b.HasIndex("VertragId")
                        .HasDatabaseName("ix_vertrags_betriebskostenrechnung_vertrag_id");

                    b.ToTable("vertrags_betriebskostenrechnung", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Verwalter", b =>
                {
                    b.Property<int>("VerwalterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("verwalter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VerwalterId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("Rolle")
                        .HasColumnType("integer")
                        .HasColumnName("rolle");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<int>("WohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnung_id");

                    b.HasKey("VerwalterId")
                        .HasName("pk_verwalter_set");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_verwalter_set_user_account_id");

                    b.HasIndex("WohnungId")
                        .HasDatabaseName("ix_verwalter_set_wohnung_id");

                    b.ToTable("verwalter_set", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Wohnung", b =>
                {
                    b.Property<int>("WohnungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wohnung_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WohnungId"));

                    b.Property<int?>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("adresse_id");

                    b.Property<int?>("BesitzerKontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("besitzer_kontakt_id");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bezeichnung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("Miteigentumsanteile")
                        .HasColumnType("double precision")
                        .HasColumnName("miteigentumsanteile");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("Nutzeinheit")
                        .HasColumnType("integer")
                        .HasColumnName("nutzeinheit");

                    b.Property<double>("Nutzflaeche")
                        .HasColumnType("double precision")
                        .HasColumnName("nutzflaeche");

                    b.Property<double>("Wohnflaeche")
                        .HasColumnType("double precision")
                        .HasColumnName("wohnflaeche");

                    b.HasKey("WohnungId")
                        .HasName("pk_wohnungen");

                    b.HasIndex("AdresseId")
                        .HasDatabaseName("ix_wohnungen_adresse_id");

                    b.HasIndex("BesitzerKontaktId")
                        .HasDatabaseName("ix_wohnungen_besitzer_kontakt_id");

                    b.ToTable("wohnungen", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Zaehler", b =>
                {
                    b.Property<int>("ZaehlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("zaehler_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZaehlerId"));

                    b.Property<int?>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("adresse_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("Ende")
                        .HasColumnType("date")
                        .HasColumnName("ende");

                    b.Property<string>("Kennnummer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kennnummer");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<int>("Typ")
                        .HasColumnType("integer")
                        .HasColumnName("typ");

                    b.Property<int?>("WohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnung_id");

                    b.HasKey("ZaehlerId")
                        .HasName("pk_zaehler_set");

                    b.HasIndex("AdresseId")
                        .HasDatabaseName("ix_zaehler_set_adresse_id");

                    b.HasIndex("WohnungId")
                        .HasDatabaseName("ix_zaehler_set_wohnung_id");

                    b.ToTable("zaehler_set", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Zaehlerstand", b =>
                {
                    b.Property<int>("ZaehlerstandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("zaehlerstand_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZaehlerstandId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notiz")
                        .HasColumnType("text")
                        .HasColumnName("notiz");

                    b.Property<double>("Stand")
                        .HasColumnType("double precision")
                        .HasColumnName("stand");

                    b.Property<int>("ZaehlerId")
                        .HasColumnType("integer")
                        .HasColumnName("zaehler_id");

                    b.HasKey("ZaehlerstandId")
                        .HasName("pk_zaehlerstaende");

                    b.HasIndex("ZaehlerId")
                        .HasDatabaseName("ix_zaehlerstaende_zaehler_id");

                    b.ToTable("zaehlerstaende", (string)null);
                });

            modelBuilder.Entity("GarageVertrag", b =>
                {
                    b.Property<int>("GaragenGarageId")
                        .HasColumnType("integer")
                        .HasColumnName("garagen_garage_id");

                    b.Property<int>("VertraegeVertragId")
                        .HasColumnType("integer")
                        .HasColumnName("vertraege_vertrag_id");

                    b.HasKey("GaragenGarageId", "VertraegeVertragId")
                        .HasName("pk_garage_vertrag");

                    b.HasIndex("VertraegeVertragId")
                        .HasDatabaseName("ix_garage_vertrag_vertraege_vertrag_id");

                    b.ToTable("garage_vertrag", (string)null);
                });

            modelBuilder.Entity("KontaktKontakt", b =>
                {
                    b.Property<int>("JuristischePersonenKontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("juristische_personen_kontakt_id");

                    b.Property<int>("MitgliederKontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("mitglieder_kontakt_id");

                    b.HasKey("JuristischePersonenKontaktId", "MitgliederKontaktId")
                        .HasName("pk_kontakt_kontakt");

                    b.HasIndex("MitgliederKontaktId")
                        .HasDatabaseName("ix_kontakt_kontakt_mitglieder_kontakt_id");

                    b.ToTable("kontakt_kontakt", (string)null);
                });

            modelBuilder.Entity("KontaktVertrag", b =>
                {
                    b.Property<int>("MieterKontaktId")
                        .HasColumnType("integer")
                        .HasColumnName("mieter_kontakt_id");

                    b.Property<int>("MietvertraegeVertragId")
                        .HasColumnType("integer")
                        .HasColumnName("mietvertraege_vertrag_id");

                    b.HasKey("MieterKontaktId", "MietvertraegeVertragId")
                        .HasName("pk_kontakt_vertrag");

                    b.HasIndex("MietvertraegeVertragId")
                        .HasDatabaseName("ix_kontakt_vertrag_mietvertraege_vertrag_id");

                    b.ToTable("kontakt_vertrag", (string)null);
                });

            modelBuilder.Entity("UmlageWohnung", b =>
                {
                    b.Property<int>("UmlagenUmlageId")
                        .HasColumnType("integer")
                        .HasColumnName("umlagen_umlage_id");

                    b.Property<int>("WohnungenWohnungId")
                        .HasColumnType("integer")
                        .HasColumnName("wohnungen_wohnung_id");

                    b.HasKey("UmlagenUmlageId", "WohnungenWohnungId")
                        .HasName("pk_umlage_wohnung");

                    b.HasIndex("WohnungenWohnungId")
                        .HasDatabaseName("ix_umlage_wohnung_wohnungen_wohnung_id");

                    b.ToTable("umlage_wohnung", (string)null);
                });

            modelBuilder.Entity("UmlageZaehler", b =>
                {
                    b.Property<int>("UmlagenUmlageId")
                        .HasColumnType("integer")
                        .HasColumnName("umlagen_umlage_id");

                    b.Property<int>("ZaehlerId")
                        .HasColumnType("integer")
                        .HasColumnName("zaehler_id");

                    b.HasKey("UmlagenUmlageId", "ZaehlerId")
                        .HasName("pk_umlage_zaehler");

                    b.HasIndex("ZaehlerId")
                        .HasDatabaseName("ix_umlage_zaehler_zaehler_id");

                    b.ToTable("umlage_zaehler", (string)null);
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Abrechnungsresultat", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Vertrag", "Vertrag")
                        .WithMany("Abrechnungsresultate")
                        .HasForeignKey("VertragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_abrechnungsresultate_vertraege_vertrag_id");

                    b.Navigation("Vertrag");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Auth.Pbkdf2PasswordCredential", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Auth.UserAccount", "User")
                        .WithOne("Pbkdf2PasswordCredential")
                        .HasForeignKey("Deeplex.Saverwalter.Model.Auth.Pbkdf2PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pbkdf2password_credentials_user_accounts_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Auth.UserAccount", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", null)
                        .WithMany("Accounts")
                        .HasForeignKey("KontaktId")
                        .HasConstraintName("fk_user_accounts_kontakte_kontakt_id");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Auth.UserResetCredential", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Auth.UserAccount", "User")
                        .WithOne("UserResetCredential")
                        .HasForeignKey("Deeplex.Saverwalter.Model.Auth.UserResetCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_reset_credentials_user_accounts_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Betriebskostenrechnung", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Umlage", "Umlage")
                        .WithMany("Betriebskostenrechnungen")
                        .HasForeignKey("UmlageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_betriebskostenrechnungen_umlagen_umlage_id");

                    b.Navigation("Umlage");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Erhaltungsaufwendung", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", "Aussteller")
                        .WithMany("Erhaltungsaufwendungen")
                        .HasForeignKey("AusstellerKontaktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_erhaltungsaufwendungen_kontakte_aussteller_kontakt_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Wohnung", "Wohnung")
                        .WithMany("Erhaltungsaufwendungen")
                        .HasForeignKey("WohnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_erhaltungsaufwendungen_wohnungen_wohnung_id");

                    b.Navigation("Aussteller");

                    b.Navigation("Wohnung");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Garage", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Adresse", "Adresse")
                        .WithMany("Garagen")
                        .HasForeignKey("AdresseId")
                        .HasConstraintName("fk_garagen_adressen_adresse_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", "Besitzer")
                        .WithMany("Garagen")
                        .HasForeignKey("BesitzerKontaktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_garagen_kontakte_besitzer_kontakt_id");

                    b.Navigation("Adresse");

                    b.Navigation("Besitzer");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.HKVO", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Umlage", "Betriebsstrom")
                        .WithMany("HKVOs")
                        .HasForeignKey("BetriebsstromUmlageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hkvo_umlagen_betriebsstrom_umlage_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Umlage", "Heizkosten")
                        .WithOne("HKVO")
                        .HasForeignKey("Deeplex.Saverwalter.Model.HKVO", "HeizkostenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hkvo_umlagen_heizkosten_id");

                    b.Navigation("Betriebsstrom");

                    b.Navigation("Heizkosten");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Kontakt", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Adresse", "Adresse")
                        .WithMany("Kontakte")
                        .HasForeignKey("AdresseId")
                        .HasConstraintName("fk_kontakte_adressen_adresse_id");

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Konto", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", "Besitzer")
                        .WithMany()
                        .HasForeignKey("BesitzerKontaktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kontos_kontakte_besitzer_kontakt_id");

                    b.Navigation("Besitzer");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Miete", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Vertrag", "Vertrag")
                        .WithMany("Mieten")
                        .HasForeignKey("VertragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mieten_vertraege_vertrag_id");

                    b.Navigation("Vertrag");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Mietminderung", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Vertrag", "Vertrag")
                        .WithMany("Mietminderungen")
                        .HasForeignKey("VertragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mietminderungen_vertraege_vertrag_id");

                    b.Navigation("Vertrag");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Umlage", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Umlagetyp", "Typ")
                        .WithMany("Umlagen")
                        .HasForeignKey("TypUmlagetypId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umlagen_umlagetypen_typ_umlagetyp_id");

                    b.Navigation("Typ");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Vertrag", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", "Ansprechpartner")
                        .WithMany("VerwaltetVertraege")
                        .HasForeignKey("AnsprechpartnerKontaktId")
                        .HasConstraintName("fk_vertraege_kontakte_ansprechpartner_kontakt_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Wohnung", "Wohnung")
                        .WithMany("Vertraege")
                        .HasForeignKey("WohnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vertraege_wohnungen_wohnung_id");

                    b.Navigation("Ansprechpartner");

                    b.Navigation("Wohnung");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.VertragVersion", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Vertrag", "Vertrag")
                        .WithMany("Versionen")
                        .HasForeignKey("VertragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vertrag_versionen_vertraege_vertrag_id");

                    b.Navigation("Vertrag");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.VertragsBetriebskostenrechnung", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Betriebskostenrechnung", "Rechnung")
                        .WithMany()
                        .HasForeignKey("RechnungBetriebskostenrechnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vertrags_betriebskostenrechnung_betriebskostenrechnungen_re");

                    b.HasOne("Deeplex.Saverwalter.Model.Vertrag", "Vertrag")
                        .WithMany()
                        .HasForeignKey("VertragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vertrags_betriebskostenrechnung_vertraege_vertrag_id");

                    b.Navigation("Rechnung");

                    b.Navigation("Vertrag");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Verwalter", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Auth.UserAccount", "UserAccount")
                        .WithMany("Verwalter")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verwalter_set_user_accounts_user_account_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Wohnung", "Wohnung")
                        .WithMany("Verwalter")
                        .HasForeignKey("WohnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verwalter_set_wohnungen_wohnung_id");

                    b.Navigation("UserAccount");

                    b.Navigation("Wohnung");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Wohnung", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Adresse", "Adresse")
                        .WithMany("Wohnungen")
                        .HasForeignKey("AdresseId")
                        .HasConstraintName("fk_wohnungen_adressen_adresse_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", "Besitzer")
                        .WithMany("Wohnungen")
                        .HasForeignKey("BesitzerKontaktId")
                        .HasConstraintName("fk_wohnungen_kontakte_besitzer_kontakt_id");

                    b.Navigation("Adresse");

                    b.Navigation("Besitzer");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Zaehler", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Adresse", "Adresse")
                        .WithMany("Zaehler")
                        .HasForeignKey("AdresseId")
                        .HasConstraintName("fk_zaehler_set_adressen_adresse_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Wohnung", "Wohnung")
                        .WithMany("Zaehler")
                        .HasForeignKey("WohnungId")
                        .HasConstraintName("fk_zaehler_set_wohnungen_wohnung_id");

                    b.Navigation("Adresse");

                    b.Navigation("Wohnung");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Zaehlerstand", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Zaehler", "Zaehler")
                        .WithMany("Staende")
                        .HasForeignKey("ZaehlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zaehlerstaende_zaehler_set_zaehler_id");

                    b.Navigation("Zaehler");
                });

            modelBuilder.Entity("GarageVertrag", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Garage", null)
                        .WithMany()
                        .HasForeignKey("GaragenGarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_garage_vertrag_garagen_garagen_garage_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Vertrag", null)
                        .WithMany()
                        .HasForeignKey("VertraegeVertragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_garage_vertrag_vertraege_vertraege_vertrag_id");
                });

            modelBuilder.Entity("KontaktKontakt", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", null)
                        .WithMany()
                        .HasForeignKey("JuristischePersonenKontaktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kontakt_kontakt_kontakte_juristische_personen_kontakt_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", null)
                        .WithMany()
                        .HasForeignKey("MitgliederKontaktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kontakt_kontakt_kontakte_mitglieder_kontakt_id");
                });

            modelBuilder.Entity("KontaktVertrag", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Kontakt", null)
                        .WithMany()
                        .HasForeignKey("MieterKontaktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kontakt_vertrag_kontakte_mieter_kontakt_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Vertrag", null)
                        .WithMany()
                        .HasForeignKey("MietvertraegeVertragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kontakt_vertrag_vertraege_mietvertraege_vertrag_id");
                });

            modelBuilder.Entity("UmlageWohnung", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Umlage", null)
                        .WithMany()
                        .HasForeignKey("UmlagenUmlageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umlage_wohnung_umlagen_umlagen_umlage_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Wohnung", null)
                        .WithMany()
                        .HasForeignKey("WohnungenWohnungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umlage_wohnung_wohnungen_wohnungen_wohnung_id");
                });

            modelBuilder.Entity("UmlageZaehler", b =>
                {
                    b.HasOne("Deeplex.Saverwalter.Model.Umlage", null)
                        .WithMany()
                        .HasForeignKey("UmlagenUmlageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umlage_zaehler_umlagen_umlagen_umlage_id");

                    b.HasOne("Deeplex.Saverwalter.Model.Zaehler", null)
                        .WithMany()
                        .HasForeignKey("ZaehlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_umlage_zaehler_zaehler_set_zaehler_id");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Adresse", b =>
                {
                    b.Navigation("Garagen");

                    b.Navigation("Kontakte");

                    b.Navigation("Wohnungen");

                    b.Navigation("Zaehler");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Auth.UserAccount", b =>
                {
                    b.Navigation("Pbkdf2PasswordCredential");

                    b.Navigation("UserResetCredential");

                    b.Navigation("Verwalter");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Kontakt", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Erhaltungsaufwendungen");

                    b.Navigation("Garagen");

                    b.Navigation("VerwaltetVertraege");

                    b.Navigation("Wohnungen");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Umlage", b =>
                {
                    b.Navigation("Betriebskostenrechnungen");

                    b.Navigation("HKVO");

                    b.Navigation("HKVOs");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Umlagetyp", b =>
                {
                    b.Navigation("Umlagen");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Vertrag", b =>
                {
                    b.Navigation("Abrechnungsresultate");

                    b.Navigation("Mieten");

                    b.Navigation("Mietminderungen");

                    b.Navigation("Versionen");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Wohnung", b =>
                {
                    b.Navigation("Erhaltungsaufwendungen");

                    b.Navigation("Vertraege");

                    b.Navigation("Verwalter");

                    b.Navigation("Zaehler");
                });

            modelBuilder.Entity("Deeplex.Saverwalter.Model.Zaehler", b =>
                {
                    b.Navigation("Staende");
                });
#pragma warning restore 612, 618
        }
    }
}
