// <auto-generated />
using Deeplex.Saverwalter.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Deeplex.Saverwalter.Model.Migrations.Npgsql
{
    [DbContext(typeof(SaverwalterContext))]
    [Migration("20260505191154_AbrechnungsresultatBuchungssatz")]
    partial class AbrechnungsresultatBuchungssatz
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
