name: feature

on:
  push:
    branches:
      - feature/*

permissions:
  contents: read

concurrency:
  group: feature-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/reusable_ci.yaml
