name: master

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

permissions:
  contents: read

concurrency:
  group: master-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/reusable_ci.yaml
  deploy_latest:
    needs: ci
    uses: ./.github/workflows/reusable_deploy_latest.yaml
