on:
  release:
    types:
      - published

jobs:
  test:
    uses: ./.github/workflows/reusable_test.yaml
  build:
    uses: ./.github/workflows/reusable_build.yaml
  deploy_release:
    needs:
      - build
    uses: ./.github/workflows/reusable_deploy_release.yaml
    with:
      tag: ${{ github.ref_name }}
